// Generated by gencpp from file trans/out_position_angle_distance.msg
// DO NOT EDIT!


#ifndef TRANS_MESSAGE_OUT_POSITION_ANGLE_DISTANCE_H
#define TRANS_MESSAGE_OUT_POSITION_ANGLE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trans
{
template <class ContainerAllocator>
struct out_position_angle_distance_
{
  typedef out_position_angle_distance_<ContainerAllocator> Type;

  out_position_angle_distance_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  out_position_angle_distance_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::trans::out_position_angle_distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trans::out_position_angle_distance_<ContainerAllocator> const> ConstPtr;

}; // struct out_position_angle_distance_

typedef ::trans::out_position_angle_distance_<std::allocator<void> > out_position_angle_distance;

typedef boost::shared_ptr< ::trans::out_position_angle_distance > out_position_angle_distancePtr;
typedef boost::shared_ptr< ::trans::out_position_angle_distance const> out_position_angle_distanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trans::out_position_angle_distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trans::out_position_angle_distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::trans::out_position_angle_distance_<ContainerAllocator1> & lhs, const ::trans::out_position_angle_distance_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::trans::out_position_angle_distance_<ContainerAllocator1> & lhs, const ::trans::out_position_angle_distance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace trans

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::trans::out_position_angle_distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trans::out_position_angle_distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trans::out_position_angle_distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trans::out_position_angle_distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trans::out_position_angle_distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trans::out_position_angle_distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trans::out_position_angle_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::trans::out_position_angle_distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::trans::out_position_angle_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trans/out_position_angle_distance";
  }

  static const char* value(const ::trans::out_position_angle_distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trans::out_position_angle_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::trans::out_position_angle_distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trans::out_position_angle_distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct out_position_angle_distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trans::out_position_angle_distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trans::out_position_angle_distance_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANS_MESSAGE_OUT_POSITION_ANGLE_DISTANCE_H
