// Generated by gencpp from file trans/position_angle_distance.msg
// DO NOT EDIT!


#ifndef TRANS_MESSAGE_POSITION_ANGLE_DISTANCE_H
#define TRANS_MESSAGE_POSITION_ANGLE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trans
{
template <class ContainerAllocator>
struct position_angle_distance_
{
  typedef position_angle_distance_<ContainerAllocator> Type;

  position_angle_distance_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , alpha(0.0)
    , beta(0.0)
    , gamma(0.0)
    , distance(0.0)  {
    }
  position_angle_distance_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , alpha(0.0)
    , beta(0.0)
    , gamma(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _alpha_type;
  _alpha_type alpha;

   typedef double _beta_type;
  _beta_type beta;

   typedef double _gamma_type;
  _gamma_type gamma;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::trans::position_angle_distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trans::position_angle_distance_<ContainerAllocator> const> ConstPtr;

}; // struct position_angle_distance_

typedef ::trans::position_angle_distance_<std::allocator<void> > position_angle_distance;

typedef boost::shared_ptr< ::trans::position_angle_distance > position_angle_distancePtr;
typedef boost::shared_ptr< ::trans::position_angle_distance const> position_angle_distanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trans::position_angle_distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trans::position_angle_distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::trans::position_angle_distance_<ContainerAllocator1> & lhs, const ::trans::position_angle_distance_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.alpha == rhs.alpha &&
    lhs.beta == rhs.beta &&
    lhs.gamma == rhs.gamma &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::trans::position_angle_distance_<ContainerAllocator1> & lhs, const ::trans::position_angle_distance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace trans

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::trans::position_angle_distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trans::position_angle_distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trans::position_angle_distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trans::position_angle_distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trans::position_angle_distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trans::position_angle_distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trans::position_angle_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af169ebc954835dea8b2e31434bb8bc4";
  }

  static const char* value(const ::trans::position_angle_distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf169ebc954835deULL;
  static const uint64_t static_value2 = 0xa8b2e31434bb8bc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::trans::position_angle_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trans/position_angle_distance";
  }

  static const char* value(const ::trans::position_angle_distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trans::position_angle_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"float64 alpha\n"
"float64 beta\n"
"float64 gamma\n"
"\n"
"float64 distance\n"
;
  }

  static const char* value(const ::trans::position_angle_distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trans::position_angle_distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.alpha);
      stream.next(m.beta);
      stream.next(m.gamma);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_angle_distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trans::position_angle_distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trans::position_angle_distance_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "alpha: ";
    Printer<double>::stream(s, indent + "  ", v.alpha);
    s << indent << "beta: ";
    Printer<double>::stream(s, indent + "  ", v.beta);
    s << indent << "gamma: ";
    Printer<double>::stream(s, indent + "  ", v.gamma);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANS_MESSAGE_POSITION_ANGLE_DISTANCE_H
