// Generated by gencpp from file arm_gazebo/IKResponse.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_IKRESPONSE_H
#define ARM_GAZEBO_MESSAGE_IKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct IKResponse_
{
  typedef IKResponse_<ContainerAllocator> Type;

  IKResponse_()
    : target_positions()  {
    }
  IKResponse_(const ContainerAllocator& _alloc)
    : target_positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _target_positions_type;
  _target_positions_type target_positions;





  typedef boost::shared_ptr< ::arm_gazebo::IKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::IKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IKResponse_

typedef ::arm_gazebo::IKResponse_<std::allocator<void> > IKResponse;

typedef boost::shared_ptr< ::arm_gazebo::IKResponse > IKResponsePtr;
typedef boost::shared_ptr< ::arm_gazebo::IKResponse const> IKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::IKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::IKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::IKResponse_<ContainerAllocator1> & lhs, const ::arm_gazebo::IKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.target_positions == rhs.target_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::IKResponse_<ContainerAllocator1> & lhs, const ::arm_gazebo::IKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::IKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::IKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::IKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::IKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::IKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::IKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::IKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03d3ed024aad438c1b5b9be5e625f68d";
  }

  static const char* value(const ::arm_gazebo::IKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03d3ed024aad438cULL;
  static const uint64_t static_value2 = 0x1b5b9be5e625f68dULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::IKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/IKResponse";
  }

  static const char* value(const ::arm_gazebo::IKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::IKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] target_positions\n"
;
  }

  static const char* value(const ::arm_gazebo::IKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::IKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::IKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::IKResponse_<ContainerAllocator>& v)
  {
    s << indent << "target_positions[]" << std::endl;
    for (size_t i = 0; i < v.target_positions.size(); ++i)
    {
      s << indent << "  target_positions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.target_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_IKRESPONSE_H
