// Generated by gencpp from file arm_gazebo/IKRequest.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_IKREQUEST_H
#define ARM_GAZEBO_MESSAGE_IKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct IKRequest_
{
  typedef IKRequest_<ContainerAllocator> Type;

  IKRequest_()
    : joint_angles()
    , link_lengths()
    , positions()  {
    }
  IKRequest_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)
    , link_lengths(_alloc)
    , positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joint_angles_type;
  _joint_angles_type joint_angles;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _link_lengths_type;
  _link_lengths_type link_lengths;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::arm_gazebo::IKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::IKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IKRequest_

typedef ::arm_gazebo::IKRequest_<std::allocator<void> > IKRequest;

typedef boost::shared_ptr< ::arm_gazebo::IKRequest > IKRequestPtr;
typedef boost::shared_ptr< ::arm_gazebo::IKRequest const> IKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::IKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::IKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::IKRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::IKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles == rhs.joint_angles &&
    lhs.link_lengths == rhs.link_lengths &&
    lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::IKRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::IKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::IKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::IKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::IKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::IKRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::IKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::IKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6297b600f34b49279cff05233d7c04be";
  }

  static const char* value(const ::arm_gazebo::IKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6297b600f34b4927ULL;
  static const uint64_t static_value2 = 0x9cff05233d7c04beULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/IKRequest";
  }

  static const char* value(const ::arm_gazebo::IKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_angles\n"
"float32[] link_lengths\n"
"float32[] positions\n"
;
  }

  static const char* value(const ::arm_gazebo::IKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::IKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
      stream.next(m.link_lengths);
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::IKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::IKRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_angles[i]);
    }
    s << indent << "link_lengths[]" << std::endl;
    for (size_t i = 0; i < v.link_lengths.size(); ++i)
    {
      s << indent << "  link_lengths[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.link_lengths[i]);
    }
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_IKREQUEST_H
